spring.application.name=expense-manager-app
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
frontend.url= ${FRONTEND_URL}
#auto update table
spring.jpa.hibernate.ddl-auto=update
security.jwt.secret-key=${JWT_KEY}
security.jwt.expiration-time=3600000
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.root= warn
